/*
 * This Source Code Form is subject to the terms of the Mozilla
 * Public License, v. 2.0. If a copy of the MPL was not distributed
 * with this file, You can obtain one at
 *
 * https://mozilla.org/MPL/2.0/.
 */

package hu.dpc.openbank.fpp.lionfintech.backend.enity.bank;

import javax.persistence.*;

@Entity
@Table(name = "ACCOUNT_CONSENT")
public class AccountConsent {
    /**
     * <pre>
     * ID                 INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 0) NOT NULL,
     * BANKID             VARCHAR(64),
     * USERNAME           VARCHAR(64),
     * CONSENTID          VARCHAR(255),
     * EXPIRES            BIGINT,
     * CONSENT_RESPONSE   VARCHAR(16777216),
     * </pre>
     */
    @Id
    @GeneratedValue
    @Column(name = "ID", nullable = false)
    private Integer    id;
    @Column(name = "BANKID", nullable = false)
    private String     bankId;
    @Column(name = "USERNAME", nullable = false)
    private String     userName;
    @Column(name = "CONSENTID")
    private String     consentId;
    @Column(name = "EXPIRES")
    private Long expires;
    @Column(name = "CONSENT_RESPONSE")
    private String     consentResponse;

    public Integer getId() {
        return id;
    }

    public void setId(final Integer id) {
        this.id = id;
    }

    public String getBankId() {
        return bankId;
    }

    public void setBankId(final String bankId) {
        this.bankId = bankId;
    }

    public String getConsentId() {
        return consentId;
    }

    public void setConsentId(final String consentId) {
        this.consentId = consentId;
    }

    public String getConsentResponse() {
        return consentResponse;
    }

    public void setConsentResponse(final String consentResponse) {
        this.consentResponse = consentResponse;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(final String userName) {
        this.userName = userName.toUpperCase();
    }

    public Long getExpires() {
        return expires;
    }

    public void setExpires(final Long expires) {
        this.expires = expires;
    }
}
